# Generated by Django 5.2.6 on 2025-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField()),
                ("ranking", models.SmallIntegerField()),
                ("book_number", models.CharField()),
                ("title", models.CharField()),
                ("book_detail", models.CharField()),
                ("book_img", models.CharField()),
                ("author", models.CharField()),
                ("publisher", models.CharField()),
                ("price", models.IntegerField()),
                ("score", models.FloatField()),
                ("num_of_review", models.IntegerField()),
                ("genre", models.CharField()),
            ],
        ),
    ]
