# Generated by Django 5.2.6 on 2025-10-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maruApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_detail",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_img",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
